### ISSUE TITLE
Feature request: allow to add volumes to the set of mounted volumes in a file that is not tracked by git

### ISSUE THREAD

**Issue by Schaechtle** [probcomp/developer#23]
Every collaborator I have worked with and I myself ended up editing the [volumes section](https://github.com/probcomp/developer/blob/77338606e0d9fd7ef0d6ae76e17f501bcc4c2f06/docker-compose.yml#L14-L20) in the `docker-compose.yml` file to mount project directories.

Edits to `docker-compose.yml` are tracked by git. It would be great if we could read additional volumes that  a user wants to mount from a separate file that is not tracked by git.

**Comment by avinson** [comment]
@Schaechtle It's possible to use a `docker-compose.override.yml` file to add additional volumes. However, if we wanted to provide an example of how this file should work, we would also need to check that into git which kind of defeats the purpose. Maybe the solution is just to add some documentation on how to use a `docker-compose.override.yml` file and add that to `.gitignore`? 

Additional info here: https://medium.com/@basi/docker-compose-from-development-to-production-88000124a57c

**Comment by avinson** [comment]
@Schaechtle see: https://github.com/probcomp/developer/commit/1d71438aa283b172854dead8068d656cd944dd88
