### ISSUE TITLE
Add robustness to developer docker image when multiple developers on the same machine/server

### ISSUE THREAD

**Issue by fsaad** [probcomp/developer#5]
Dockerized development on a shared server, where multiple users have their own running containers against a shared `probcomp/notebook:latest' image, is likely to face issues with isolation.

Add some explicit guidelines to help ensure that their images/containers/ports remain isolated. Below are some failure modes I anticipate, and possible solutions:

1. The `probcomp/notebook:latest` dockerfile is not version controlled. If user X runs `docker pull probcomp/notebook:latest`, then this will also result in  user Y obtaining the update, without them knowing.
- [ ] Solution 1: Tell developers to create docker tags to pin their images.
- [ ] Solution 2: Version the probcomp/notebook dockerfiles.

2. The docker containers live in a shared namespace. Therefore, if two users run `docker-compose up` separately, they may wipe one another's containers.
- [ ] Tell developers to use `docker-compose -p <username> up`.
- [ ] Update `docker-compose exec' command in bootstrap accordingly.

3. The docker-compose.yml hard-codes port 8888. Therefore, users will not be able to run containers simultaneously.
- [ ] Document to users that they may need to change 8888:8888 in `docker-compose.yml' to something else like 8889:8888 (until it works).

**Comment by avinson** [comment]
@fsaad docker image tagging/versioning is valuable and I think we should discuss/implement it at some point but let's discuss that in a separate thread. I've incorporated your other suggestions here.
