### ISSUE TITLE
Suggestions to improve step-by-step getting started guide for documentation

### ISSUE THREAD

**Issue by fsaad** [probcomp/developer#6]
What we need is a step-by-step guide that holds the user's hand, assuming they are arriving with a completely clean slate: install docker/docker-compose, clone the Github repos, pull the notebook image from dockerhub, etc, to be written clearly and detailed systematically

A list of items to cover might be something like:

Step 1: Ask your system maintainer to install docker (>1.13) and docker-compose (>1.19).
Step 2: Ask your system maintainer to add you to the docker group.
Step 3: Run `docker pull probcomp/notebook:latest` to get the base image.
Step 4: Run `git clone` on bayeslite/cgpm/crosscat/iventure/developer ...
Step 5: Run `cd developer, then run `docker-compose up -p <username>`
Step 6: Run `make bootstrap`
Step 7: ...

**Comment by avinson** [comment]
I believe I covered the majority of the additional documentation you've requested. Please reopen the issue if you disagree.
